import sys
from reportlab.lib.pagesizes import letter
from reportlab.pdfgen import canvas
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer,  Table, Image
from reportlab.lib.enums import TA_JUSTIFY, TA_LEFT, TA_CENTER
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import cm
def generatePDF(datain, img1,  outfile):
	styles=getSampleStyleSheet()
	styles.add(ParagraphStyle(name='Justify', alignment=TA_JUSTIFY))
	styles.add(ParagraphStyle(name='Center', alignment=TA_CENTER))
	doc = SimpleDocTemplate(outfile,pagesize=letter,
	                        rightMargin=72,leftMargin=72,
	                        topMargin=72,bottomMargin=18)
	Story=[]
	img_pygal=img1
	Story.append(Paragraph("GO Terms distribution report", styles["title"]))
	Story.append(Spacer(1, 12))
	im1 = Image(img_pygal, 19.5*cm, 13.7*cm)
	Story.append(im1)
	Story.append(Spacer(1, 1))
	Story.append(Paragraph("Image generated by PyGal", styles['Center']))
	Story.append(Spacer(1, 10))
	Story.append(Paragraph("Table with distribution", styles["h1"]))
	data=[(Paragraph("Go term", styles['h3']),Paragraph("Count", styles['h3']), Paragraph("Percentage", styles['h3']))]
	data.extend(datain)
	table = Table(data, colWidths=170, rowHeights=20)
	Story.append(table)
	Story.append(Spacer(1, 10))
	Story.append(Paragraph("Pdf generated by AFAMS 0.1", styles['Center']))
	doc.build(Story)

def loadData(file_name):
	archivo=open(file_name,"r")
	arreglos=[]
	suma=0
	for line in archivo:
		linea=line.replace("\n","").split("\t")
		arreglos.append(linea)
		suma+=int(linea[1])
	for i in range(len(arreglos)):
		arreglos[i].append("%.3f" % (float(arreglos[i][1])/suma) + "%")
	for i in range(len(arreglos)):
		arreglos[i]=tuple(arreglos[i])
	data=arreglos
	return data

def usage():
	print """ Generates a PDF report with the output of AFAMS
	PdfGen.py GoCount.tab Report.pdf image.png
	"""
	exit()
def main():
	if len(sys.argv)<4:
		usage()
	img_pygal=sys.argv[3]
	data_file=sys.argv[1]
	outfile=sys.argv[2]
	data=loadData(data_file)
	generatePDF(data, img_pygal, outfile)
	print "The PDF report has been generated on %s" %outfile

main()